server {
    # Nginx 80 portunu (Standart HTTP portu) dinler
    listen 80;
    
    # Sunucu adı (Lokalde localhost, canlıda api.slotra.com olacak)
    server_name localhost;

    # Gelen tüm istekleri ( / ) arka plandaki API'ye yönlendir
    location / {
        # DİKKAT: Burada 'api' yazmasının sebebi docker-compose'daki servis adının api olmasıdır!
        proxy_pass http://api:3000;
        
        # Orijinal kullanıcının IP adresini ve bilgilerini API'ye aktar (Çok önemli)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}